name: Release Charts

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart version to release'
        required: true
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Debug - List helmchart contents
        run: |
          echo "Contents of helmchart directory:"
          ls -R helmchart

      - name: Debug - Print Chart Version
        run: |
          echo "Chart version:"
          grep 'version:' helmchart/Chart.yaml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: helmchart
          config: cr.yaml

      - name: Force release if needed
        if: failure()
        run: |
          cr package helmchart
          cr upload --skip-existing
          cr index --push
